// <auto-generated />
using System;
using DBdesign.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBdesign.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230719091359_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBdesign.Shared.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sss@gmail.com",
                            Name = "Ben",
                            Phone = "0966666666",
                            Position = "engineer",
                            PunchId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sssss@gmail.com",
                            Name = "Alan",
                            Phone = "0977777777",
                            Position = "engineer",
                            PunchId = 2
                        });
                });

            modelBuilder.Entity("DBdesign.Shared.Punchs1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PunchIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PunchOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PunchId");

                    b.ToTable("Punchs1", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hours = "",
                            Name = "Ben",
                            PunchId = 1,
                            PunchIn = new DateTime(2023, 7, 19, 17, 13, 59, 495, DateTimeKind.Local).AddTicks(2714),
                            PunchOut = new DateTime(2023, 7, 19, 17, 13, 59, 495, DateTimeKind.Local).AddTicks(2723),
                            Time = "2023/07/19"
                        },
                        new
                        {
                            Id = 2,
                            Hours = "",
                            Name = "Ben",
                            PunchId = 1,
                            PunchIn = new DateTime(2023, 7, 19, 17, 13, 59, 495, DateTimeKind.Local).AddTicks(2724),
                            PunchOut = new DateTime(2023, 7, 19, 17, 13, 59, 495, DateTimeKind.Local).AddTicks(2725),
                            Time = "2023/07/19"
                        });
                });

            modelBuilder.Entity("DBdesign.Shared.Punchs2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PunchIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PunchOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PunchId");

                    b.ToTable("Punchs2", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hours = "",
                            Name = "Alan",
                            PunchId = 2,
                            PunchIn = new DateTime(2023, 7, 19, 17, 13, 59, 495, DateTimeKind.Local).AddTicks(3189),
                            PunchOut = new DateTime(2023, 7, 19, 17, 13, 59, 495, DateTimeKind.Local).AddTicks(3190),
                            Time = "2023/07/19"
                        });
                });

            modelBuilder.Entity("DBdesign.Shared.Punchs1", b =>
                {
                    b.HasOne("DBdesign.Shared.Employees", "Employee")
                        .WithMany("Punch1")
                        .HasForeignKey("PunchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DBdesign.Shared.Punchs2", b =>
                {
                    b.HasOne("DBdesign.Shared.Employees", "Employee")
                        .WithMany("Punch2")
                        .HasForeignKey("PunchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DBdesign.Shared.Employees", b =>
                {
                    b.Navigation("Punch1");

                    b.Navigation("Punch2");
                });
#pragma warning restore 612, 618
        }
    }
}
